[build]
command = "npm run build"
publish = "build"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]
  "Cache-Control" = "public, max-age=31560000, immutable"

[build.environment]
  SESSION_SECRET = "7gZfSqVQSHS9M9c/x9YVBSRPq+E1T/M6jN8dybzRhUY=" 
  GOOGLE_CLIENT_ID = "1079234336489-rkeiomsnsejcfb670qt1riph0gvcpv62.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET = "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"
  APP_BASE_URL = "https://jdc-portal-grenoble.netlify.app/"
  GOOGLE_APPLICATION_CREDENTIALS = "app/services/google-credentials.json"
