[build]
command = "npm run build"
publish = "build/client" # ✅ pour servir correctement les assets

[functions]
  [functions.command]
  framework = "vite"
  external_node_modules = ["firebase-admin"]

  [functions.sap_notifications]
  name = "sap-notifications"
  schedule = "*/5 * * * *"

  [functions.gmail_processing]
  name = "scheduled-gmail-processing"
  schedule = "*/60 * * * *"

  [functions.kezia_check]
  name = "check-kezia-installations"
  schedule = "*/15 * * * *"

  [functions.sync_installations]
  name = "sync-installations"
  schedule = "*/60 * * * *"

[[headers]]
for = "/assets/*" # ✅ vise bien les fichiers d'assets, pas "/build/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
  SESSION_SECRET = "7gZfSqVQSHS9M9c/x9YVBSRPq+E1T/M6jN8dybzRhUY=" 
  GOOGLE_CLIENT_ID = "1079234336489-rkeiomsnsejcfb670qt1riph0gvcpv62.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET = "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"
  APP_BASE_URL = "https://jdc-portal-grenoble.netlify.app/"
