[build]
command = "npm run build"
publish = "build"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]
  "Cache-Control" = "public, max-age=31560000, immutable"

[build.environment]
  SESSION_SECRET = "7gZfSqVQSHS9M9c/x9YVBSRPq+E1T/M6jN8dybzRhUY=" 
  GOOGLE_CLIENT_ID = "1079234336489-rkeiomsnsejcfb670qt1riph0gvcpv62.apps.googleusercontent.com" # Please set your Google Client ID
  GOOGLE_CLIENT_SECRET = "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" # Please set your Google Client Secret
  APP_BASE_URL = "https://jdc-portal-grenoble.netlify.app/" # Please set your app base URL
  GOOGLE_APPLICATION_CREDENTIALS = "app/services/google-credentials.json" # Path to Google credentials file
  FIREBASE_PROJECT_ID = "sap-jdc" # Please set your Firebase project ID
  FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCQ3dBcuEomcqxy\nzN57bGNhdh/V0Asshoc0HWW8CI2Uko2DgwEMgna9gxOlWshLzgcfAJk3s1FzPQFl\nAorgXDuu2f/7rETekRHg3HFyBpLCymcO99m6Mo3SRjw0SJ2abPj8UAhfzHxvdJAk\nxctQVsMVLgN5pF8udBymUT4PI04O8yCQgiN8B4nelZotrSKLxunDQI3uETmVvzNF\nsrK5mpSPf0Y05AZ/p9Vn+wpjP+u6F6Ic47v7GN81eq+LANIeB6B+cRzY9GSJ79gG\nXot83zP07ooQPWsVbgsrGAJraHrzvx/L+a8DVk7eClaY9FU1iucKJmynqW7w1c/t\nONnkyLWPAgMBAAECggEACRGBlhRJO//osKUHdlVyISs6UfGciXSAaTA/6pXkevzz\nk9xzB9vw3+shIzQ8Hpaulm+8p6J3gk261R5kIChV6humbRQ7GW2eX2OdTGSB8mSm\nL+cu/3tjqlqQMTusdfrFWVIPPCP6VCXJUiv5jrVnr986A3bZKHjHRFgImPz+SWwx\np/I9O6nm7anTTspeNiRTIIAFUXaK1EwGWdv/WmO7tTjpSAojTLltN2uq8+xyAIvf\nF+EkmNNJkFdQw83kTdfp3A4Kf/JcE240DR6TQIhJQ98Ckl9DN9q4LIl5LmSabeIF\npl03ht3WhvLcZqx7oQ9awGTQ0vRwHbXti6WvWQF3IQKBgQDIeLWh7Iqk6LEFNBUT\n4gmmIHy6imdHcHCF1XFT5trVZRVWNgOkJmTpsoXuKfQszx/s2Fe9666U3DthVNN4\noNe7TD984AurXuplwDupo4l77rSDJEHUhqnq8hRHZazyevwV2mNEZAd8hiE5iYhP\nd18MJZMuL0dI0Xr8lQI7cl+k7wKBgQC4/jCWCLl63/FwNqxuWrTKxqrgbp+5ntej\nbiyj2IQF3mbpKm/6lZ7HVq13Ws/CeafDgr7xvO2mwabSdoiypTQoN3kSEsB5KGIM\n8iL73QuZYCkWt3OUXckFx6dtB449t1pj7tmpDJyUdHdNsxthqCUQqsGoISFnSoCX\nzSjcHk45YQKBgQC/COhs6XAlPeiSwNLlI512RbcWPBW3KhrQLlnUTkVy3OS8RrSp\nlDzNxmWCU1Bv8uDFXlQek5zGFigv1BnA9eUegsZtRUNZhxVu6QTx3vmAtDQoVEC3\nOaxqS02vy+bHIZNfb8DwxzGrJFY88iaHM4XLmXLrq/oOFjFQyN5br94c2QKBgQCu\n89bHTeD8kCYqVcqlYytwSor4TibIyaxuZ5fYLMBPPJJfGT9l4XKUWykao8uwxJUg\nldo3jNHEz4gRqwCE0zCMiEn8Cbf13Xc9fxIO2HJLz2GMllq8iiW/TZ7NwkOHoovd\nztoSwlajH7JkzWqr5PWI2bTkaNDKeu86oVBvPEoGgQKBgBca36oCuj+0sDftgCTU\nRrL8EXpUkv25ZtEiZqgZBODrB3VUZNkXNzh2Ht94G8ZU3+OklIPulse7P+Zqxugs\nnh7dHwQ0ZT5Ktv3AOEEoFQIBH1459rkBuMjrJZs/UHiBC086+2PGILu59rso9vt1\n2uZ/CkfB3iQfz4cBHG4mpPhv\n-----END PRIVATE KEY-----\n" # Please set your Firebase private key
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@sap-jdc.iam.gserviceaccount.com" # Please set your Firebase client email
  FIREBASE_API_KEY = "AIzaSyADAy8ySvJsUP5diMyR9eIUgtPFimpydcA"
